export const FETCH_USERS = 'FETCH_USERS';
export const RECEIVE_USERS_SUCCESS = 'RECEIVE_USERS_SUCCESS';
export const RECEIVE_USERS_FAILURE = 'RECEIVE_USERS_FAILURE';

export const ADD_USER = 'ADD_USER';

export const FETCH_ROLES = 'FETCH_ROLES';
export const RECEIVE_ROLES_SUCCESS = 'RECEIVE_ROLES_SUCCESS';
export const RECEIVE_ROLES_FAILURE = 'RECEIVE_ROLES_FAILURE';